# **Google Colab warm-up tutorial**

# **What is Google Colab and how is it used?**

Colab is a hosted Jupyter Notebook service that offers the advantage of providing free access to computing resources. Also, Colab enables learning data science, bioinformatics data analysis, and various STEAM education topics.

In the following, we will review the components and functionalities that GoogleColab presents, but we recommend watching the [introduction to colab video](https://www.youtube.com/watch?v=inN8seMm7UI) to learn more about this resource.

The most relevant function of Colab is that it allows writing code and text through a list of cells that can be seen throughout its interface. Therefore, the user can add a new cell using the **+ CODE** and **+ TEXT** buttons located at the top. Also, each new cell can be jumped up or down depending on the desired location within the dashboard.

Look to the top left, where you will find four icons. The first one you can see is the following one:

 ><img src="https://upload.wikimedia.org/wikipedia/commons/b/bb/Summary_icon.svg" width="100">

 Figure 1. Content icon [1]

The figure 1 corresponds to the table of contents of the jupyter notebook. The last icon corresponds to the file explorer of the virtual machine assigned to your session, which can be connected directly to an assigned Google Drive path.

**Text cells**

In Google Colab there are two different types of cells: text and code. Text cells use markdown formatting, based on the [original markdown project](https://daringfireball.net/projects/markdown/syntax). Users can double-click to start editing cells that use markdown syntax, which you can review in the next section.

**Markdown**

The text cells in Google Colab are in markdown format and are divided into two columns. The left column corresponds to the source code where the user can make the necessary adjustments or add relevant information to his notebook. On the other hand, the right column corresponds to the rendered version of the code. In addition, the text cells have a toolbar at the top for easy editing.

The following are specific and useful examples of how to use the markdown format.

**Text Formats:**

\**italics*\* or \__italics__

**\*\*bold\*\***

\~\~~~strikethrough~~\~\~

\``monospace`\`

**List**
*   Item 1
*   Item 2
*   Item 3

**Ordered list:**
1. 1\. One
1. 1\. Two
1. 1\. Three

**Unordered list:**
* \* One
* \* Two
* \* Three

**Code cells**

The execution of the code cells is conditional on the user connecting to a runtime hosted in the virtual machine. Likewise, the user has the option to connect locally to its resources. To be able to connect, we must go to the top menu and click on "Connect".

 <img src='https://media.giphy.com/media/lRLBURv0hpcHqiraBI/giphy.gif'/>

Figure 2. Connection to Google colab.

Once connected, the code cell can be executed by clicking on the play button in the same cell or Ctrl/+ Enter.


In [1]:
# An example of implementation

A = 'Bacillus paranthracis'
B = 'Bacillus xiamenensis'
A,B

('Bacillus paranthracis', 'Bacillus xiamenensis')

# **Introduction to Python commands**

At this point it is important to address the Python programming language that Google Colab implements. You may be wondering: What is Python and how does it work?

Python is a widely used programming language because of its features:

* **Interpreted language:** This feature allows the code execution to be done line by line. This is a great help when finding errors in the code structure.

* **Untyped language:** In python it is not necessary to declare variables before using them, because they are determined at runtime.

* **High-level language:** Structure and memory capacity are not an issue to worry about in this programming language.

* **Object-oriented language:** Phyton considers everything as an object, but supports structured and functional programming.

Below we discuss the basic syntax for using python.

**Python syntax**

Python in Colab notebooks can be written directly from code cells:

In [2]:
print("Welcome to Python")

Welcome to Python


Python uses indentation as a block indicator for its code:

In [3]:
if 10 < 21:
  print("Ten is less than twenty-one")

Ten is less than twenty-one


Python allows us to comment code using the # sign, so that characters after this sign will not be taken into account.

In [4]:
# This line implements a condition

x = 1
if x > 16:
    print("x is greater than 2") # Over 16
else:
    print("x is not greater than 2") # Under 16

x is not greater than 2


Now you may be wondering how to create a variable, because we have already implemented it before. Here we show you how to create a variable. Remember that in python you don't need to declare the variable, but you can change a variable from one type to another.

In [5]:
x = 3             # x is a variable of type int
y  = "Sally"      # y is a variable of type str
print(x)
print(y)

3
Sally


To change the type of variable we can execute the following commands.

In [6]:
x = str(5)      # x corresponds to '5'
y = int(5)      # y corresponds to 5
z = float(5)    # z corresponds to 5.0

print(x)
print(y)
print(z)

5
5
5.0


**Data types**

In the Python programming language there is a fundamental concept called data type. The variables we have created so far can store different types of data that can have different functionalities.

Below, we show the built-in and most commonly used data types.

| Example                             | Data Type    |
|-------------------------------------|--------------|
| x = "Welcome to python"             | str          |
| x = 18                              | int          |
| x = 18.5                            | float        |
| x = 5j                              | complex      |
| x = ["lulo", "apple", "papaya"]     | list         |
| x = ("lulo", "apple", "papaya")     | tuple        |
| x = range(6)                        | range        |
| x = {"name" : "Camilo", "age" : 36} | dict         |
| x = {"lulo", "apple", "papaya"}     | set          |
| x = True                            | bool         |

**1. String**

In python a string is defined as a text string that is specified between single quotes or double quotes.

In [7]:
print("Getting started tutorial")
print("Python programming language")


Getting started tutorial
Python programming language


In the strings we can get a range of characters that we want to use.

In [8]:
a = "Getting started tutorial"
print(a[2:6])

ttin


Another possibility is to concatenate different strings named in different variables.

In [11]:
a = "Getting "
b = "started "
c = "tutorial"

d = a + b + c

print(d)

Getting started tutorial


Also this data type (String) has different methods associated with it. Some of the associated methods are shown below.

In [12]:
a = "getting started tutorial"
c = "GETTING STARTED TUTORIAL"

# Convertir el primer caracter a mayúscula

b = a.capitalize()
print(b)

# Convertir todo el string a minúscula

d = c.casefold()
print(d)

# Podemos implementar un separador en nuestro String
g = a.split(" ")
print(g)

Getting started tutorial
getting started tutorial
['getting', 'started', 'tutorial']


**2. Numeric values**

Three types of numerical data are present in Python:

* Integers = int
* Floating point numbers = float
* Complex numbers = complex

In [13]:
a = 7 # int
b = 2.8 # float
c = 3j  # complex

print(a)
print(b)
print(c)

7
2.8
3j


**3. Boolean**

Booleans are used in Python to evaluate an expression where you can get two possible answers: True or False.

Examples are shown below.

In [14]:
# The following expressions are evaluated
print(49 < 2)
print(91 > 28)
print(34 == 12)

False
True
False


In [ ]:
# Another possibility is to assess a condition.

a = 200
b = 33

if b > a:
  print("True")
else:
  print("False")

**4. List**

It is one of the four data types used by python to store multiple items. Lists are characterised as an ordered and modifiable collection. The following shows how to create a list.

In [15]:
# Creation of a list
list = ["red", "blue", "green", "orange"]

print(list)

['red', 'blue', 'green', 'orange']


In [16]:
# A list can store different types of data

listA = ["Hello", True, False, 15, 3, 2, "value1"]
print(listA)

['Hello', True, False, 15, 3, 2, 'value1']


Lists have methods that allow you to sort, add, change and delete items. You can also split a list into two or join two different lists.

In [18]:
listA = ["red", "blue", "green", "orange"]
listB = ["cat", "dog", "bird", "bear"]
listC = ["mathematics", "biology", "chemistry", "physics"]
listD = [1, 2, 5, 9, 9, 14, 14, 14, 13]

# Change an item in the list

listA[2] = "green"
print(list)

# Add an item to the list

listB.append("caterpillar")
print(listB)

# Remove an item from the list

listC.remove("biology")
print(listC)

# Sort list

listB.sort()
print(listB)

# Join lists

listE = listA + listB
print(listE)

['red', 'blue', 'green', 'orange']
['cat', 'dog', 'bird', 'bear', 'caterpillar']
['mathematics', 'chemistry', 'physics']
['bear', 'bird', 'cat', 'caterpillar', 'dog']
['red', 'blue', 'green', 'orange', 'bear', 'bird', 'cat', 'caterpillar', 'dog']


**5. Tuples**

Tuples are a data type that allows storing different elements. They differ from lists because they are an ordered and immutable collection. Also, when defining a tuple it is important to remember that they are written inside square brackets.

In [19]:
# Create a tuple

tuple = ('bird', 'cat', 'caterpillar', 'bear', 'dog')
print(tuple)

('bird', 'cat', 'caterpillar', 'bear', 'dog')


In [20]:
# Some methods we can use with this type of data:
# Join tuples

tuple1 = ('bird', 'cat', 'caterpillar', 'bear', 'dog')
tuple2 = (1, 3, 7, 12, 16, 31)
tuple3 = ('mathematics', 'chemistry', 'physics')

tuple4 = tuple1 + tuple2
print(tuple3)

# Access an element of the tuple

print(tuple3[1])

('mathematics', 'chemistry', 'physics')
chemistry


**6. set**

The third of the elements that python uses to store data. A set is an unordered, unmodifiable, non-indexed, unordered collection.

In [21]:
# Create a set

set1 = {'bird', 'cat', 'cat', 'caterpillar', 'bear', 'dog', 'bird'}
print(set1)

{'cat', 'bird', 'caterpillar', 'dog', 'bear'}


In [22]:
# Some methods we can use with this type of data:
# Join sets

set1 = {'bird', 'cat', 'caterpillar', 'bear', 'dog'}
set2 = {1, 3, 7, 12, 16, 31}
set3 = {'mathematics', 'chemistry', 'physics'}

set4 = set1.union(set2)
print(set4)

# Access an element in the set

print("cat" in set1)

# Add an element

set2.add(24)
print(set2)

# Remove an element

set3.remove("chemistry")
print(set3)

{1, 'cat', 3, 7, 'bird', 'caterpillar', 12, 'bear', 16, 'dog', 31}
True
{16, 1, 3, 7, 24, 12, 31}
{'mathematics', 'physics'}


**7. Dictionary**

Python dictionaries are the fourth type of storage data and are used to store values in pairs (key:value). This data type is an unordered, non-modifiable, non-indexed collection.

In [23]:
dic = {
    "name": "Juan Andrés",
    "height": 1.79,
    "age": 28,
    "city": "Bogotá"
}

print(dic)

{'name': 'Juan Andrés', 'height': 1.79, 'age': 28, 'city': 'Bogotá'}


In [27]:
# Some methods we can implement with dictionaries will be shown below.
# How can we get a value from the dictionary?
# This can be done through "get" and placing the key of which we want to have information.

dic = {
    "name": "Carlos",
    "Height": 1.82,
    "Age": 31,
    "City": "Ibagué"
}

A = dic.get("Height")
print(A)

# We can also add a new item to the dictionary

B = dic.keys()
print(B)

dic["Job title"] = "Researcher"
print(B)

print(dic)

# Change a dictionary item

dic["Profession"] = "Engineer"
print(dic)

# Delete item

dic.pop("Profession")
print(dic)

1.82
dict_keys(['name', 'Height', 'Age', 'City'])
dict_keys(['name', 'Height', 'Age', 'City', 'Job title'])
{'name': 'Carlos', 'Height': 1.82, 'Age': 31, 'City': 'Ibagué', 'Job title': 'Researcher'}
{'name': 'Carlos', 'Height': 1.82, 'Age': 31, 'City': 'Ibagué', 'Job title': 'Researcher', 'Profession': 'Engineer'}
{'name': 'Carlos', 'Height': 1.82, 'Age': 31, 'City': 'Ibagué', 'Job title': 'Researcher'}


# **Python modules**

Python allows you to work with code belonging to self-made modules or default modules. A module can be thought of as a library of code that contains a set of functions that we want to include in our lines of code.

The two modules we will cover in this tutorial series are Numpy and Pandas.  

The basic commands and functionalities for each of them will be explained below.

**1. Numpy**

Numpy is a Python library that is commonly used to work with arrays. This is due to its fast and versatile concepts applied to vectorisation and indexing.

The following is an explanation of the library's functionalities.

In [28]:
# Import the library

import numpy

# Create an array

array = numpy.array([3,6 ,9 ,12 ,14, 42])

print(array)

[ 3  6  9 12 14 42]


Numpy can generally be used with the alias **np** and it is also recommended to check the implemented version of numpy.

In [33]:
# Import numpy with the alias np

import numpy as np

# Create an array

array = np.array([3,6 ,9 ,12 ,14, 42])

print(array)

# Check version of numpy

print(np.__version__)

[ 3  6  9 12 14 42]
1.25.2


Can we create arrays of more than one dimension? Yes, we can create arrays of different dimensions and implement different methods for each one.

In [36]:
# Zero-dimensional array

Array_1 = np.array(21)

# One dimensional array

Array_2 = np.array([3,5,9,10,12])

# Two-dimensional array

Array_3 = np.array([[3,5,9], [13 ,17,19]])

# Three-dimensional array

Array_4 = np.array([[[3,5,9], [13 ,17,19]], [[1,7,9], [25, 29, 30]]])

# Print arrays

print(Array_1)
print(Array_2)
print(Array_3)
print(Array_4)


# Print array dimensions

print(Array_1.ndim)
print(Array_2.ndim)
print(Array_3.ndim)
print(Array_4.ndim)

21
[ 3  5  9 10 12]
[[ 3  5  9]
 [13 17 19]]
[[[ 3  5  9]
  [13 17 19]]

 [[ 1  7  9]
  [25 29 30]]]
0
1
2
3


The first method to implement is indexing. This allows us to access any element in the array.

In [41]:
# Array creation

Array_1 = np.array(21)
Array_2 = np.array([3,5,9,10,12])
Array_3 = np.array([[3,5,9], [13 ,17,19]])
Array_4 = np.array([[[3,5,9], [13 ,17,19]], [[1,7,9], [25, 29, 30]]])

# Access the third element of the one-dimensional array

print(Array_2[3])

# Access second element of second row, third column

print("Second element of the second row and third column: ", Array_3[1, 2])

# Access the first row and second column of the second array

print(Array_4[1, 0, 1])

10
Second element of the second row and third column:  19
7


Other methods that can be implemented with Numpy include the ability to join, split, search and sort array elements.

In [42]:
# Join arrays

Array_1 = np.array([3,5,9,10,12])

Array_2 = np.array([21, 14, 32, 5, 9])

Array_3 = np.concatenate((Array_1, Array_2))

print(Array_3)

# Split arrays in two

Array_5 = np.array_split(Array_3, 2)

print(Array_5)

# Find the index where the value is 10 of array 1

A = np.where(Array_1 == 10)

print(A)

# Sort array 2

print(np.sort(Array_2))

[ 3  5  9 10 12 21 14 32  5  9]
[array([ 3,  5,  9, 10, 12]), array([21, 14, 32,  5,  9])]
(array([3]),)
[ 5  9 14 21 32]


**2. Pandas**

Pandas is a Python library used in data science to analyse, clean, explore and manipulate data. Below, we will show you how to import the pandas module and its various functionalities.

In [44]:
import pandas

dataset = {
    'Student': ["John", "George", "Alexander", "Louis"],
    'Age': [20, 18, 19, 25]
}

table = pandas.DataFrame(dataset)

print(table)

     Student  Age
0       John   20
1     George   18
2  Alexander   19
3      Louis   25


Pandas can generally be used with the alias **pd** and it is also recommended to check the implemented version of pandas.

In [46]:
# Implement the pd alias

import pandas as pd

dataset = {
    'Students': ["John", "George", "Alexander", "Louis"],
    'Age': [20, 18, 19, 25]
}

table = pd.DataFrame(dataset)

print(table)

# check pandas version

print(pd.__version__)

    Students  Age
0       John   20
1     George   18
2  Alexander   19
3      Louis   25
2.0.3


Before creating our first table through pandas it is important to understand the concepts of **series** and **tags**. A series corresponds to a one-dimensional array containing any type of data and in pandas it corresponds to a column of a table. On the other hand, a tag corresponds to the index provided to a group of elements. For example, if no index is specified in a table, the first value will be indexed as 0.

In [47]:
# Create a series

A = [1, 3, 5]

series1 = pd.Series(A)
print(series1)

# Access the third label or index

print(series1[2])

# We can also create our own indexes

series2 = pd.Series(A, index = ["A", "B", "C"])
print(series2)

0    1
1    3
2    5
dtype: int64
5
A    1
B    3
C    5
dtype: int64


One of the most used functions of pandas is the creation of data tables and the possibility to manage and clean these data.

In [49]:
# Creation of a data table

data1 = {
    "name": [ "John", "David", "Alexander", "Doris", "Nixon"],
    "age": ["21", "19", "23", "20", "25"],
    "gender": ["M", "M", "M", "F", "M"]
}

df = pd.DataFrame(data1)

print(df)

        name age gender
0       John  21      M
1      David  19      M
2  Alexander  23      M
3      Doris  20      F
4      Nixon  25      M


In [51]:
# Change the indexes of a table

data1 = {
    "name": [ "John", "David", "Alexander", "Doris", "Nixon"],
    "age": ["21", "19", "23", "20", "25"],
    "gender": ["M", "M", "M", "F", "M"]
}

# Add an ID per student as its index
df = pd.DataFrame(data1, index = [20162341, 20161012, 20152354, 20184524, 20199981])

print(df)

               name age gender
20162341       John  21      M
20161012      David  19      M
20152354  Alexander  23      M
20184524      Doris  20      F
20199981      Nixon  25      M


Pandas allows importing files with comma separated values (csv).

In [52]:
# You can test this command by uploading a .csv file to your workspace and changing iris.csv to your file.

df2 = pd.read_csv('iris.csv')

print(df2)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


We can also obtain information from the iris table.

In [53]:
# Define table

df = pd.read_csv('iris.csv')

# Print the first 10 rows of the table

print(df.head(10))

# Print the last 10 rows of the table

print(df.tail(10))

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa
     sepal.length  sepal.width  petal.length  petal.width    variety
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8   

Pandas allows us to clean up our data table by removing empty cells or repeated data.

In [58]:
# Creation of data table with repeated values and empty cells
data = {
    "name": ["John", "David", "Alexander", "Doris", "Nixon", "John", "David", None],
    "age": [21, 19, 23, None, 25, 21, 19, 30],
    "gender": ["M", "M", "M", "F", "M", "M", "M", None]
}

df = pd.DataFrame(data)

# Print the data table
print(df)

# Delete empty cells from the table

New_df = df.dropna()

print(New_df.to_string())

# Remove duplicates

New_df.drop_duplicates(inplace = True)
print(New_df)

        name   age gender
0       John  21.0      M
1      David  19.0      M
2  Alexander  23.0      M
3      Doris   NaN      F
4      Nixon  25.0      M
5       John  21.0      M
6      David  19.0      M
7       None  30.0   None
        name   age gender
0       John  21.0      M
1      David  19.0      M
2  Alexander  23.0      M
4      Nixon  25.0      M
5       John  21.0      M
6      David  19.0      M
        name   age gender
0       John  21.0      M
1      David  19.0      M
2  Alexander  23.0      M
4      Nixon  25.0      M


<ipython-input-58-347e44861b42>:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_df.drop_duplicates(inplace = True)


# **Biopython**

Biopython is a set of freely available tools for biological computing written in Python. It contains different libraries that allow us to perform sequence alignment, analysis of GFF files, phylogenetic analysis and analysis of protein crystal structures.

In [59]:
# Biopython installation

!pip install biopython

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 30.5 MB/s eta 0:00:00


If you want to learn more about the different modules of this tool you can check the [documentation](https://biopython.org/). In our case we will focus on the **Bio.PDB** module which focuses on working with crystalline structures of macromolecules such as proteins.

In [60]:
# Import from Bio.PDB

from Bio.PDB import*

It is important when using this module to have your PDB file in your work path. The PDB file can be obtained from the database [Protein Data Bank](https://www.rcsb.org/) and in our case we are going to work with the structure whose ID 4EY6. This crystal structure corresponds to recombinant human acetylcholinesterase in complex with galantamine.

To obtain the PDB file you have to type in the search area the ID 4EY6 and press 'Enter' to obtain the entry corresponding to the access code together with the information associated to the protein structure.

Another way to retrieve the protein structure is to do it directly in Google Colab using the url through the **wget** command.

In [61]:
# Recovery of the protein with ID 4EY6

!wget http://www.rcsb.org/pdb/files/4EY6.pdb.gz
!gunzip 4EY6.pdb.gz

--2024-06-25 19:33:33--  http://www.rcsb.org/pdb/files/4EY6.pdb.gz
Resolving www.rcsb.org (www.rcsb.org)... 128.6.159.248
Connecting to www.rcsb.org (www.rcsb.org)|128.6.159.248|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.rcsb.org/pdb/files/4EY6.pdb.gz [following]
--2024-06-25 19:33:33--  https://www.rcsb.org/pdb/files/4EY6.pdb.gz
Connecting to www.rcsb.org (www.rcsb.org)|128.6.159.248|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://files.rcsb.org/download/4EY6.pdb.gz [following]
--2024-06-25 19:33:33--  https://files.rcsb.org/download/4EY6.pdb.gz
Resolving files.rcsb.org (files.rcsb.org)... 128.6.159.245
Connecting to files.rcsb.org (files.rcsb.org)|128.6.159.245|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 189281 (185K) [application/octet-stream]
Saving to: ‘4EY6.pdb.gz’

4EY6.pdb.gz         100%[===================>] 184.84K  --.-KB/s    in 0.03s 

Once we have our crystal structure we can create the Biopython object.

In [62]:
# Create PDB object
parser = PDBParser()

# Next we define the structure as an object

structure = parser.get_structure("GAL", "4EY6.pdb")

/usr/local/lib/python3.10/dist-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 9016.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 9045.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 9117.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 9321.
  warnings.warn(


Once we create our PDB object we can navigate through it to obtain relevant information.

In [63]:
# Iteration over all atoms of the structure
p = PDBParser()
structure = p.get_structure("X", "4EY6.pdb")
for model in structure:
    for chain in model:
        for residue in chain:
            for atom in residue:
                print(atom)

/usr/local/lib/python3.10/dist-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 9016.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 9045.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 9117.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 9321.
  warnings.warn(


Streaming output truncated to the last 5000 lines.
<Atom CD>
<Atom OE1>
<Atom NE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom NE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom NE>
<Atom CZ>
<Atom NH1>
<Atom NH2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom OE2>


In [64]:
# Iterate over all atoms in the structure.

for atom in structure.get_atoms():
    print(atom)

# Iterate over all residues in the structure

for residue in model.get_residues():
    print(residue)

Streaming output truncated to the last 5000 lines.
<Atom CZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom NE>
<Atom CZ>
<Atom NH1>
<

There are a lot of resources and methods offered by this Biopython module. Therefore, if you want to learn more about its functionality you can access its [documentation](https://biopython.org/wiki/The_Biopython_Structural_Bioinformatics_FAQ).